You died.
Better luck next life.

A horrible scream wakes you up.
You were caught by a car accident and
now undead monsters crawl the street.
Emily...your wife...
Is she alright?
You have to go home and find her!

You are home now.
Thank god. Emily's fine.
You find out that military has
set up a camp for town people.
Now go there and survive!

You are late. Emily's gone.
You bury her in the yard.
But there's no time for sadness.
There's a camp set up by military.
No go there and survive!

Congratulations!
You are a true survivor!
